"""Loader for PACDEL band-power CSV extractions.

The 188 CSVs in Related/pacdel_csv/ were batch-generated by Len Trejo
(PACDEL) on 2013-01-25 from the raw BDF recordings.  Each CSV contains
per-60-second-window band power averages and cumulative reward counts
for a single neurofeedback training session.

Filename convention: A{subject}_{day}_{L|S}_{date}.csv
  - day: 1-5 consecutive training days (not BDF session numbers)
  - L = Live (veridical feedback), S = Sham (active placebo)
  - date: recording date (YYYY-MM-DD)

Mapping to BDF sessions is done by matching recording dates from the
BDF headers (stored in study.json session_dates).
"""

from __future__ import annotations

import logging
import re
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import pandas as pd

from .config import RELATED_ROOT

logger = logging.getLogger(__name__)

PACDEL_DIR = RELATED_ROOT / "pacdel_csv"

BAND_COLUMNS = {
    "Avg 4.0-7.0": "theta",
    "Avg 7.0-9.0": "alpha1",
    "Avg 9.0-11.0": "alpha2",
    "Avg 12.0-15.0": "smr",
    "Avg 15.0-18.0": "beta",
    "Avg 22.0-30.0": "high_beta",
}

_FNAME_RE = re.compile(
    r"A(\d{3})_(\d+[a-z]?)_([LS])_(\d{4}-\d{2}-\d{2})\.csv"
)


def parse_filename(name: str) -> Optional[Tuple[str, str, str, str]]:
    """Extract (subject, day_label, group_code, date) from a CSV filename."""
    m = _FNAME_RE.match(name)
    if not m:
        return None
    return m.group(1), m.group(2), m.group(3), m.group(4)


def load_pacdel_session(path: Path) -> pd.DataFrame:
    """Load a single PACDEL CSV into a DataFrame."""
    df = pd.read_csv(path)
    info = parse_filename(path.name)
    if info:
        subj, day, grp, date = info
        df["subject"] = subj
        df["pacdel_day"] = day
        df["group_code"] = grp
        df["recording_date"] = date
    return df


def _build_date_to_session(session_dates: Dict[str, str]) -> Dict[str, int]:
    """Invert session_dates {session_num: date} to {date: session_num}."""
    return {date: int(sess) for sess, date in session_dates.items()}


def load_pacdel_subject(
    subject: str,
    session_dates: Optional[Dict[str, str]] = None,
    pacdel_dir: Path = PACDEL_DIR,
) -> pd.DataFrame:
    """Load all PACDEL CSVs for a subject, optionally mapping to BDF sessions."""
    frames = []
    for csv_path in sorted(pacdel_dir.glob(f"A{subject}_*_*.csv")):
        df = load_pacdel_session(csv_path)
        frames.append(df)

    if not frames:
        logger.warning("No PACDEL CSVs found for subject %s", subject)
        return pd.DataFrame()

    result = pd.concat(frames, ignore_index=True)

    if session_dates:
        date_map = _build_date_to_session(session_dates)
        result["bdf_session"] = result["recording_date"].map(date_map)
    else:
        result["bdf_session"] = pd.NA

    return result


def load_pacdel_all(
    study_json_path: Optional[Path] = None,
    pacdel_dir: Path = PACDEL_DIR,
) -> pd.DataFrame:
    """Load all PACDEL CSVs into a single long-form DataFrame.

    If *study_json_path* is provided, maps recording dates to BDF session
    numbers using the session_dates field from study.json.
    """
    import json

    session_lookup: Dict[str, Dict[str, str]] = {}
    if study_json_path and study_json_path.is_file():
        for rec in json.loads(study_json_path.read_text()):
            session_lookup[rec["subject_id"]] = rec.get("session_dates", {})

    frames = []
    for csv_path in sorted(pacdel_dir.glob("A*_*_*.csv")):
        info = parse_filename(csv_path.name)
        if not info:
            continue
        subj = info[0]
        df = load_pacdel_session(csv_path)
        if subj in session_lookup:
            date_map = _build_date_to_session(session_lookup[subj])
            df["bdf_session"] = df["recording_date"].map(date_map)
        else:
            df["bdf_session"] = pd.NA
        frames.append(df)

    if not frames:
        return pd.DataFrame()

    result = pd.concat(frames, ignore_index=True)
    logger.info("Loaded %d PACDEL rows across %d files", len(result), len(frames))
    return result


def load_pacdel_long(
    study_json_path: Optional[Path] = None,
    pacdel_dir: Path = PACDEL_DIR,
) -> pd.DataFrame:
    """Load PACDEL data in tidy long form (one row per subject/session/period/band)."""
    wide = load_pacdel_all(study_json_path, pacdel_dir)
    if wide.empty:
        return wide

    id_cols = [
        "subject", "pacdel_day", "group_code", "recording_date",
        "bdf_session", "Seconds", "Period", "rewTotal",
    ]
    band_cols = [c for c in BAND_COLUMNS if c in wide.columns]
    existing_id = [c for c in id_cols if c in wide.columns]

    long = wide.melt(
        id_vars=existing_id,
        value_vars=band_cols,
        var_name="band_raw",
        value_name="power",
    )
    long["band"] = long["band_raw"].map(BAND_COLUMNS)
    long.drop(columns=["band_raw"], inplace=True)
    return long


def validate_group_assignments(
    pacdel_dir: Path = PACDEL_DIR,
) -> Dict[str, str]:
    """Extract group assignments from PACDEL L/S filename coding.

    Returns {subject_id: 'L' or 'S'} for independent validation against
    study.json group assignments.
    """
    assignments: Dict[str, str] = {}
    for csv_path in pacdel_dir.glob("A*_*_*.csv"):
        info = parse_filename(csv_path.name)
        if not info:
            continue
        subj, _, grp, _ = info
        if subj in assignments and assignments[subj] != grp:
            logger.warning(
                "Subject %s has mixed L/S codes in PACDEL filenames", subj,
            )
        assignments[subj] = grp
    return assignments
